# permissions for end users to view machinedeletions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletion-viewer-role
rules:
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions/status
  verbs:
  - get
