# permissions for end users to edit machinedeletiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletiontemplate-editor-role
rules:
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletiontemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletiontemplates/status
  verbs:
  - get
