# permissions for end users to edit machinedeletions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletion-editor-role
rules:
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions/status
  verbs:
  - get
