# permissions for end users to view machinedeletiontemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinedeletiontemplate-viewer-role
rules:
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletiontemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletiontemplates/status
  verbs:
  - get
