
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions/finalizers
  verbs:
  - update
- apiGroups:
  - machine-deletion.medik8s.io
  resources:
  - machinedeletions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.openshift.io
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
