name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: go get github.com/jstemmer/go-junit-report
      - run: go test ./... -coverprofile=cover.out  | go-junit-report > report.xml
#      - run: npm install -g bats
#      - run: bats -v
