name: Pre Submit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make manager

    - name: Test
      run: make test

    - name: Run codacy-coverage-reporter
      run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}  --language go --force-coverage-parser go -r cover.out

    - name: TestMutations
      run: make test-mutation-ci